### ISSUE TITLE
Divide-by-zero error in Fontextension.cs  (UWP)

### ISSUE THREAD

**Issue by KCarterSr** [baskren/Forms9Patch#12]
In the new release i'm getting a divide-by-zero exception in your code.

Here are some useful snapshots.

Fontextension.cs 
![2019-07-02_14-18-59](https://user-images.githubusercontent.com/2046991/60536839-2721bb80-9cd5-11e9-95d7-344e54c7ee5c.jpg)

LabelRenderer.cs
![2019-07-02_14-28-42](https://user-images.githubusercontent.com/2046991/60537158-e4141800-9cd5-11e9-9531-6a9bc2071c1b.jpg)

**Comment by baskren** [comment]
Could you send me a stack trace?

**Comment by KCarterSr** [comment]
Ok, I've tracked down in my code, what is triggering the error.
See the screen-shot that explains what the cause is.

I'm also added the stack-trace you requested.

Thanks

![2019-07-02](https://user-images.githubusercontent.com/2046991/60602789-7b36a980-9d82-11e9-8a1b-ba4682121375.jpg)

   at Xamarin.Forms.Size..ctor(Double width, Double height)
   at Forms9Patch.UWP.LabeLRenderer.GetDesiredSize(Double widthConstraint, Double heightConstraint)
   at Xamarin.Forms.Platform.UWP.Platform.GetNativeSize(VisualElement element, Double widthConstraint, Double heightConstraint)
   at Xamarin.Forms.Platform.UWP.WindowsBasePlatformServices.GetNativeSize(VisualElement view, Double widthConstraint, Double heightConstraint)
   at Xamarin.Forms.VisualElement.OnSizeRequest(Double widthConstraint, Double heightConstraint)
   at Forms9Patch.Label.OnSizeRequest(Double widthConstraint, Double heightConstraint)
   at Xamarin.Forms.VisualElement.OnMeasure(Double widthConstraint, Double heightConstraint)
   at Forms9Patch.Label.OnMeasure(Double widthConstraint, Double heightConstraint)
   at Xamarin.Forms.VisualElement.GetSizeRequest(Double widthConstraint, Double heightConstraint)
   at Forms9Patch.Label.GetSizeRequest(Double widthConstraint, Double heightConstraint)
   at Xamarin.Forms.VisualElement.Measure(Double widthConstraint, Double heightConstraint, MeasureFlags flags)
   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)
   at Xamarin.Forms.Grid.LayoutChildren(Double x, Double y, Double width, Double height)
   at Xamarin.Forms.Layout.UpdateChildrenLayout()
   at Xamarin.Forms.Layout.OnSizeAllocated(Double width, Double height)
   at Xamarin.Forms.VisualElement.SizeAllocated(Double width, Double height)
   at Xamarin.Forms.Layout.<>c.<OnChildMeasureInvalidated>b__45_0()
   at Xamarin.Forms.Platform.UWP.WindowsBasePlatformServices.<>c__DisplayClass3_0.<BeginInvokeOnMainThread>b__0()

**Comment by baskren** [comment]
version 1.8.0.1 has been released
