### ISSUE TITLE
Version 2.2.6- Release Error: "LinkAssembiles task failed unexpectedly"

### ISSUE THREAD

**Issue by jxiong-art** [baskren/Forms9Patch#49]
Hi, I'm testing my app deployment/publish. My app is able to run good in debug mode, but when I rebuild in release mode I get this error:
```
The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Int32 Forms9Patch.Droid.TextControlState::GetHashCode()' in assembly: 'Forms9Patch.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 System.HashCode::Combine(!!0)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	BatteryTruck.Android			
```

I have the latest Android version: Android 9.0 and min/max Android target version.
Xamarin Forms v4.5.0.530
Visual Studios 2017 Professional Edition

Please let me know if you are able to assist me or if I am doing something wrong.

Much appreciated!

**Comment by jxiong-art** [comment]
From an earlier issue#26: https://github.com/baskren/Forms9Patch/issues/26
I see that Visual Studios 2019 works, therefore was wondering if there was a solution in Visual Studios 2017.

And to confirm, testing in Visual Studios 2019 Community Edition, I am able to rebuild successfully on Release Mode, but not in Visual Studios 2017.

**Comment by baskren** [comment]
Bummer.  I can't help you on this one.  Seems like more of a Microsoft / Visual Studio issue.
