### ISSUE TITLE
[Bug] build failed on AndroidX

### ISSUE THREAD

**Issue by Minamiyama** [baskren/Forms9Patch#77]
### Description
I got error message when I build my project for AndroidX,
here is the messages:

Error		Mono.Linker.MarkException: Error processing method: 'System.Void xxx.Droid.Resource::UpdateIdValues()' in assembly: 'xxx.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 Forms9Patch.Droid.Resource/Animation::btn_checkbox_to_checked_box_inner_merged_animation
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	Olist.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1645	

- Version with issue: 2.4.6
- IDE: VS 2019 16.7.3
- Platform Target Frameworks:
  - Android: Android 10

**Comment by baskren** [comment]
Demo project?

**Comment by Minamiyama** [comment]
It seems okay in an new empty project, let me check more
